name: Build APK

on:
  push:
    branches:
      - main  # Change this to your default branch name if different
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'  # Use the Temurin distribution for JDK

    - name: Download Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30  # Set to the API level your project targets
        build-tools: 30.0.3  # Set to the build tools version your project requires

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APK
      run: ./gradlew assembleRelease  # Use assembleDebug for debug builds

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
